services:
  taskflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.deploy
    image: taskflow:deploy
    container_name: taskflow_249
    ports:
      - '5700:5700'
    environment:
      QlBaseUrl: '/'
      QlPort: '5700'
      BACK_PORT: '5700'
      GRPC_PORT: '5600'
      NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org/'
      npm_config_registry: 'https://registry.npmjs.org/'
      PIP_BREAK_SYSTEM_PACKAGES: '1'
    volumes:
      - ./data:/ql/data
    restart: unless-stopped
